apiVersion: neajmorshad.dev.neajmorshad.com/v1beta1
kind: Kluster
metadata:
  name: kluster-sample-2
spec:
  replicas: 2
  container:
    image: "neajmorshad/http-api-server:0.0.2"
    port: 8080
  service:
    serviceName: "my-service-2"
    serviceType: "ClusterIP"
    servicePort: 8080
