apiVersion: neajmorshad.dev.neajmorshad.com/v1beta1
kind: Kluster
metadata:
  name: kluster-sample-1
spec:
  name: my-deployment-1
  replicas: 3
  container:
    image: "neajmorshad/http-api-server:0.0.2"
    port: 8080
  service:
    serviceName: "my-service"
    serviceType: "ClusterIP"
    servicePort: 8080
